### ISSUE TITLE
Update setup.cfg before deploying plugin

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/napari-n2v#1]
Just a small task: Update setup.cfg before submitting this project to pypi. Otherwise, generic email-addresses and github-urls will cause issues on pypi and napari-hub:
https://github.com/juglab/napari-n2v/blob/064b8dd0efef3ac12e8ca9b725af4f74ffab5871/setup.cfg#L5

I also propose to change the intended audience and topic here:
https://github.com/juglab/napari-n2v/blob/064b8dd0efef3ac12e8ca9b725af4f74ffab5871/setup.cfg#L13
and 
https://github.com/juglab/napari-n2v/blob/064b8dd0efef3ac12e8ca9b725af4f74ffab5871/setup.cfg#L15

to something like this:
https://github.com/haesleinhuepf/napari-skimage-regionprops/blob/bda457cb30d15c057669e3cd847ab5e795c4b75d/setup.py#L44-L47

**Comment by jdeschamps** [comment]
Good catch! Thanks!
Fixed in https://github.com/juglab/napari-n2v/commit/fef4e213e539c6dbdca79230c6b77b803c7008ca.
