### ISSUE TITLE
Installation instructions for Windows

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/napari-n2v#2]
Just a note/hint: The installation instructions presented for Linux users here:
https://juglab.github.io/napari-n2v/installation.html

... also work for me on Windows. I do have an NVidia GPU though.

**Comment by jdeschamps** [comment]
Great! Then I added the mention in https://github.com/juglab/napari-n2v/commit/eb889e65c12eb6721eb7a227a92bc75b785384a6.
