### ISSUE TITLE
Provide small example dataset + trained model?

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/napari-n2v#3]
After clicking on File > Open Samples > napari-n2c > Download data (2D) napari freezes. After a while, a 3D image with 3000+ slices is opened. 

Would it be possible to provide a single small 2D image + a trained model users can quickly open to try out napari-n2v?

**Comment by jdeschamps** [comment]
I added a notification to warn users about download times.

Providing a trained network and a small example is a great idea! Two ways I see:
- open the prediction plugin with the network already loaded (requires changing the widget parameters), but this would need access to the Viewer from a sample file (not sure how legal and elegant that is).
- guide users through loading them from the hidden folder where files are downloaded

**Comment by jdeschamps** [comment]
In https://github.com/juglab/napari-n2v/commit/38a42c8e9c9b3a1339dd4f314dd23af943436e66:
- new plugin that downloads and load a single SEM image and a trained model, users can directly press "predict"
