### ISSUE TITLE
No way to disable data augmentation during patch creation

### ISSUE THREAD

**Issue by nunopimpaomartins** [juglab/napari-n2v#32]
I could not find any option or setting to disable data augmentation for patch creation when training a new model.

Could be useful when there is already lots of data and no augmentation is wanted.

Napari version: 0.4.15
napari-n2v version: 0.0.4

**Comment by jdeschamps** [comment]
Added to https://github.com/juglab/napari-n2v/commit/d8fd394249efda05f804efa6d8f5bf2c6f8ad531
