### ISSUE TITLE
Icons missing in the interface of the plugin

### ISSUE THREAD

**Issue by nunopimpaomartins** [juglab/napari-n2v#33]
All the icons are missing from the interface when loading the plugin in my system. All space appears blank.

Looks like:
![missingicons](https://user-images.githubusercontent.com/16762812/201399681-d769d935-8233-4ec4-ae94-b2e6453b396b.png)

OS: Windows 10
Napari: 0.4.15
napari-n2v: 0.04

**Comment by jdeschamps** [comment]
Should be fixed here: https://github.com/juglab/napari-n2v/pull/40
