### ISSUE TITLE
Cannot set more than 20 val patches when loading data from layers

### ISSUE THREAD

**Issue by nunopimpaomartins** [juglab/napari-n2v#34]
When loading data for training from existing layers, it is not possible to assign more than 20 patches for Validation.

Additionally, it should say in the tooltip it is an absolute number and not relative/fraction of existing patches.

**Comment by jdeschamps** [comment]
Fixed in https://github.com/juglab/napari-n2v/commit/6ab844d157d2202bb2634ca45a7656bec34e7668
