### ISSUE TITLE
Predicted layer has different pixel size than input data

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/napari-n2v#36]
After training, when predicting a new image, the new layer added to napari has pixel size `[1,1]`. If the original input data had a different pixel size, the images do not fit to each other.

Workaround: In the console of napari, you can transfer the pixel size of one layer to another like this
```
viewer.layers[-1].scale = viewer.layers[0].scale
```

CC @Thawn

**Comment by jdeschamps** [comment]
Thanks for the feedback!

I will tackle all the outstanding issues after the holiday season. :)

**Comment by jdeschamps** [comment]
Happy new year then ^^

This should be fixed in https://github.com/juglab/napari-n2v/commit/9d26f8463c5c97cf74ee6afb945d3a3f46398860
