### ISSUE TITLE
Trailer image / banner / graphical abstract

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/napari-n2v#4]
When deploying the plugin to pypi, a page on the napari hub will be created that is identical with the readme of the github repository. I recommend putting a screenshot of the plugin, e.g. showing a noisy and a denoised image, on top of the page as a graphical abstract. Users tend to not read the documentation. To give them a glimpse what the plugin does, that screenshot might help.

**Comment by jdeschamps** [comment]
Love the idea!

**Comment by jdeschamps** [comment]
Done in https://github.com/juglab/napari-n2v/commit/b9604125737402597ff72806782488a9846e6de5
