### ISSUE TITLE
Interoperability with napari-workflows / napari-assistant

### ISSUE THREAD

**Issue by haesleinhuepf** [juglab/napari-n2v#6]
I was browsing the code for a function that might be compatible with [napari-workflows](https://github.com/haesleinhuepf/napari-workflows) and the [napari-assistant](https://www.napari-hub.org/plugins/napari-assistant). If there was one, people could combine n2v denoising with deconvolution. deskewing, segmentation etc. without the need for coding skills in fully automated workflows. I'm CC-ing @pr4deepr who I'm sure will be excited to put napari-n2v in one of his workflows as part of [napari-lattice](https://github.com/BioimageAnalysisCoreWEHI/napari_lattice/wiki/5.-Workflows-(Interactive:-no-coding)#workflow).

To make napari-n2v compatible, we would need some function with a signature such as:
```
def denoise(input_image: "napari.types.ImageData", model_filename:str) -> "napari.types.ImageData":
   ...
```

I'm wondering if this makes sense? I wrote a similar function earlier, but I'm not sure if the file format is compatible with napari-n2v. If you think it makes sense and can guide me a bit, I'm happy to provide a PR. E.g. let me know where in the code-base this could go. Here is what I programmed earlier:

```
from napari_tools_menu import register_function
from napari_time_slicer import time_slicer

@register_function(menu="Filtering / noise removal > Apply noise2void denoiser")
@time_slicer
def apply_noise2void(image: "napari.types.ImageData",
                       model_filename: str = "my_model_n2v",
                       number_of_tiles: int = 4,
                      ) -> "napari.types.ImageData":
    """
    Parameters
    ----------
    image
    model_filename
    Returns
    -------
    See Also
    --------
    ..[0] https://github.com/juglab/n2v/blob/master/examples/3D/02_prediction.ipynb
    ..[1] https://github.com/juglab/n2v/blob/master/examples/2D/denoising2D_SEM/02_prediction.ipynb
    """
    if len(model_filename) == 0:
        raise Exception("No model chosen")

    from n2v.models import N2V
    import numpy as np

    basedir = 'models'
    model = N2V(config=None, name=model_filename, basedir=basedir)
    if len(image.shape) == 2:
        axes = "YXC"
        tiles = (number_of_tiles, number_of_tiles, 1)
    elif len(image.shape) == 3:
        axes = "ZYXC"
        tiles = (number_of_tiles, number_of_tiles, number_of_tiles, 1)
    else:
        raise ValueError("Only 2D and 3D data supported.")

    predicted_image = model.predict(image[..., np.newaxis], axes=axes, n_tiles=tiles)
    return predicted_image[..., 0]
```

Napari would then generate a user-interface from this function signature automatically that looks like that:
![image](https://user-images.githubusercontent.com/12660498/192135986-e098d125-dbcf-4775-91ec-9edeea0c1f07.png)

The function would then show up in the assistant like this:
![image](https://user-images.githubusercontent.com/12660498/192135999-2fa79250-bf8d-4f1a-b55c-22562a03e8db.png)

**Comment by pr4deepr** [comment]
Thanks for tagging me on this post @haesleinhuepf . Will b super cool to add this to napari-lattice!

**Comment by haesleinhuepf** [comment]
> Do you have any assumption in the axes order? Any constraints on the output shape?

Napari typically considers TZYX the axis order. When working with 2D+t data, I use T1YX, to prevent napari showing time as third spatial axis.

If you annotate the function with `@time_slicer`, it will never receive a 4D stack. It will always receive the current 2D/3D timepoint. See the documentation for details:
https://www.napari-hub.org/plugins/napari-time-slicer

**Comment by jdeschamps** [comment]
Alright. Is the model name supposed to be a path (str) ?
